future: true
permalink: /:title/
url: http://DaveGao.github.io
name: Dave Gao
author: Dave Gao
qq: 1078983625
email: 1078983625@qq.com

duoshuo: Dave Gao
beian: 
cnzz: 
weibo: 
github: DaveGao
about: "创建于2018年3月10日"

safe: true
paginate: 20
